#include "hw_gpio.h"

void GPIO_USART1_Init(void)
{
  RCC-> APB2ENR |= RCC_APB2ENR_IOPAEN;
  GPIOA-> CRH &= ~GPIO_CRH_CNF9;
  GPIOA-> CRH |= GPIO_CRH_CNF9_1;
  GPIOA-> CRH |= GPIO_CRH_MODE9_0;
  GPIOA-> CRH &= ~GPIO_CRH_CNF10;
  GPIOA-> CRH |= GPIO_CRH_CNF10_0;
  GPIOA-> CRH &= ~GPIO_CRH_MODE10;
}

void GPIO_LED_Init(void)
{
  RCC-> APB2ENR |= RCC_APB2ENR_IOPBEN;
  GPIOB-> CRL &= ~GPIO_CRL_MODE2_0;
  GPIOB-> CRL |= GPIO_CRL_MODE2_1;
  GPIOB-> CRL &= ~GPIO_CRL_CNF2_0;
  GPIOB-> CRL &= ~GPIO_CRL_CNF2_1;
}